import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'App ByUsers',
  description: 'Generated ByUsers',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
 <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
  <link href="https://fonts.googleapis.com/css2?family=Caramel&family=Courgette&family=Dancing+Script:wght@700&family=EB+Garamond&family=Great+Vibes&family=Heebo:wght@300&family=Mochiy+Pop+One&family=Nunito+Sans:ital,wght@0,500;1,400&family=Nunito:ital,wght@0,200;1,400&family=Playfair+Display:wght@500&family=Poppins:wght@300;600&family=Public+Sans:wght@200&family=Roboto:ital,wght@0,100;0,300;0,700;0,900;1,100;1,300;1,400&display=swap" rel="stylesheet" 
  />
    </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
